apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-auth

resources:
# Authentication and rate limiting policies for the gateway
- gateway-auth-policy.yaml
- token-limit-policy.yaml
- rate-limit-policy.yaml