# OpenShift Route for Gateway access with policy enforcement
# 
# This route provides controlled access to AI models through the Gateway which:
#   - Enforces authentication via AuthPolicy
#   - Applies rate limiting via TokenRateLimitPolicy
#   - Routes to appropriate model backends based on HTTPRoutes
#
# All model inference requests should use this gateway endpoint
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway-route
  namespace: openshift-ingress
  labels:
    app: openshift-ai-inference
    gateway: openshift-ai-inference
spec:
  host: gateway.apps.test-maas-v1.eh5f.s1.devshift.org
  port:
    targetPort: 80
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: openshift-ai-inference-openshift-default
    weight: 100
  wildcardPolicy: None 