---
# Qwen3-0.6B Model serving with vLLM for OpenShift
# Small but capable model perfect for testing GPU serving on OpenShift
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Qwen3-0.6B-Instruct
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: "false"
  name: qwen3-0-6b-instruct
  namespace: llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    serviceAccountName: kserve-service-account
    nodeSelector:
      nvidia.com/gpu.present: "true"
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    model:
      modelFormat:
        name: vLLM
      name: ''
      storageUri: hf://Qwen/Qwen3-0.6B
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: vllm-latest
      env:
        - name: HF_TOKEN
          value: ""
        - name: HOME
          value: "/tmp"
        - name: XDG_CACHE_HOME
          value: "/tmp/.cache"
        - name: VLLM_CACHE_ROOT
          value: "/tmp/vllm_cache"
        - name: TRITON_CACHE_DIR
          value: "/tmp/triton_cache"
        - name: FLASHINFER_WORKSPACE_DIR
          value: "/tmp/flashinfer_cache"

