---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: "vLLM Latest with Qwen3 Support (OpenShift)"
    opendatahub.io/template-display-name: "vLLM Latest with Qwen3 Support (OpenShift)"
    opendatahub.io/template-name: vllm-latest-openshift
    sidecar.istio.io/inject: "false"
  name: vllm-latest
  namespace: llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --distributed-executor-backend=mp
        - --max-model-len=6144
        - --trust-remote-code
        - --gpu-memory-utilization=0.8
        - --max-num-seqs=32
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: spawn
      image: 'vllm/vllm-openai:latest'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /tmp
          name: tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000960000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
      resources:
        limits:
          nvidia.com/gpu: '1'
        requests:
          nvidia.com/gpu: '1'
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
    - emptyDir:
        sizeLimit: 4Gi
      name: tmp