apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: key-manager-dev

resources:
- ../../base/

secretGenerator:
- name: key-manager-admin-secret
  behavior: replace
  literals:
  - admin-api-key=letmein