apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: custom-wasm-shim

# Patch the Kuadrant operator to use custom wasm-shim for token metrics
patches:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: kuadrant-operator.v0.0.0
    namespace: kuadrant-system
  patch: |-
    - op: replace
      path: /spec/install/spec/deployments/0/spec/template/spec/containers/0/env/1/value
      value: "oci://ghcr.io/nerdalert/wasm-shim:latest"