apiVersion: v1
kind: Service
metadata:
  name: key-manager
spec:
  selector:
    app.kubernetes.io/name: key-manager
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  type: ClusterIP
