# This transformer is to prevent from overwriting the namespace in Gateway resource.
# It needs to be openshift-ingress for having cluster DNSRecord
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-gateway-namespace
patch: |-
  - op: replace
    path: /metadata/namespace
    value: openshift-ingress
target:
  group: gateway.networking.k8s.io
  version: v1
  kind: Gateway
