apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authorino-runtime
  namespace: kuadrant-system
  labels:
    environment: base
    project: models-aas-observability
spec:
  selector:
    matchLabels:
      authorino-resource: authorino
      control-plane: controller-manager
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
    - port: http
      path: /server-metrics
      interval: 10s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: limitador-runtime
  namespace: kuadrant-system
  labels:
    environment: base
    project: models-aas-observability
spec:
  selector:
    matchLabels:
      app: limitador
      limitador-resource: limitador
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
