apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authorino-runtime
  namespace: kuadrant-system
  labels:
    environment: base
    project: models-aas-observability
spec:
  selector:
    matchLabels:
      authorino-resource: authorino
      control-plane: controller-manager
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
    - port: http
      path: /server-metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: limitador-runtime
  namespace: kuadrant-system
  labels:
    environment: base
    project: models-aas-observability
spec:
  selector:
    matchLabels:
      app: limitador
      limitador-resource: limitador
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: user-workload-prometheus
  namespace: llm-observability
spec:
  datasource:
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    name: user-workload-prometheus
    secureJsonData:
      httpHeaderValue1: Bearer ${token}
    type: prometheus
    url: https://prometheus-user-workload.openshift-user-workload-monitoring.svc.cluster.local:9091
  instanceSelector:
    matchLabels:
      app: grafana
  valuesFrom:
    - targetPath: secureJsonData.httpHeaderValue1
      valueFrom:
        secretKeyRef:
          key: token
          name: grafana-sa-token