# Security Context Constraints for KServe InferenceServices on OpenShift
# This allows model containers to run with the required security permissions
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-service-account
  namespace: llm
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kserve-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowPrivilegeEscalation: true
allowedCapabilities:
- NET_ADMIN
- NET_RAW
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:llm:kserve-service-account
- system:serviceaccount:llm:default
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- hostPath
