apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-gpu-deployment-openshift

# GPU cluster with both models (without infrastructure - deployed separately)
resources:
- ../kustomize-templates/models/simulator
- ../kustomize-templates/models/qwen3
- ../kustomize-templates/auth/api-keys
- ../kustomize-templates/auth/token-rate-limiting
- ../kustomize-templates/observability
