---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-manager
  namespace: platform-services
  labels:
    app: key-manager
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-manager
  template:
    metadata:
      labels:
        app: key-manager
        version: v2
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: key-manager
      securityContext:
        runAsNonRoot: true
      containers:
      - name: key-manager
        image: ghcr.io/redhat-et/maas-key-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: KEY_NAMESPACE
          value: llm
        - name: SECRET_SELECTOR_LABEL
          value: kuadrant.io/apikeys-by
        - name: SECRET_SELECTOR_VALUE
          value: rhcl-keys
        - name: PORT
          value: "8080"
        - name: CREATE_DEFAULT_TEAM
          value: "true"
        - name: TOKEN_RATE_LIMIT_POLICY_NAME
          value: "gateway-token-rate-limits"
        - name: AUTH_POLICY_NAME
          value: "gateway-auth-policy"
        - name: ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: key-manager-admin
              key: admin-key
        - name: GIN_MODE
          value: "debug"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: key-manager
  namespace: platform-services
  labels:
    app: key-manager
spec:
  selector:
    app: key-manager
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
