# KServe Configuration for Kuadrant Integration on OpenShift
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  storageInitializer: |-
    {
        "image" : "kserve/storage-initializer:v0.15.2",
        "memoryRequest": "4Gi",
        "memoryLimit": "8Gi",
        "cpuRequest": "2",
        "cpuLimit": "4",
        "caBundleConfigMapName": "",
        "caBundleVolumeMountPath": "/etc/ssl/custom-certs",
        "enableDirectPvcVolumeMount": true,
        "enableModelcar": true,
        "cpuModelcar": "10m",
        "memoryModelcar": "15Mi",
        "uidModelcar": 1010
    }
  logger: |-
    {
        "image" : "kserve/agent:v0.15.2",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "defaultUrl": "http://default-broker"
    }
  batcher: |-
    {
        "image" : "kserve/agent:v0.15.2",
        "memoryRequest": "1Gi",
        "memoryLimit": "1Gi",
        "cpuRequest": "1",
        "cpuLimit": "1",
        "maxBatchSize": "32",
        "maxLatency": "5000"
    }
  agent: |-
    {
        "image" : "kserve/agent:v0.15.2",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
  ingress: |-
    {
        "enableGatewayApi": true,
        "kserveIngressGateway": "openshift-ingress/openshift-ai-inference",
        "ingressGateway": "istio-system/istio-ingressgateway",
        "ingressDomain": "example.com"
    }
  deploy: |-
    {
        "defaultDeploymentMode": "RawDeployment"
    }
