apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-api-secrets-provider

resources:
- ../../base/

patches:
- path: patches/secrets-provider.yaml
- path: patches/clusterrole.yaml
  target:
    kind: ClusterRole
    name: maas-api
