apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-kuadrant-openshift

# OpenShift-specific kuadrant configuration
resources:
- https://github.com/Kuadrant/kuadrant-operator//config/install/openshift?ref=main
