apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-service-account
  namespace: llm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kserve-service-account
  namespace: llm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-manager-role
subjects:
- kind: ServiceAccount
  name: kserve-service-account
  namespace: llm 