apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qwen3-0-6b-instruct

namespace: llm

resources:
- kserve-service-account.yaml
- vllm-runtime.yaml
- qwen3-model.yaml
- httproute.yaml
- rbac.yaml