apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qwen3-single-node-no-scheduler-nvidia-gpu

namespace: llm

# Note: namePrefix causes issues with KServe-generated service names
# The LLMInferenceService creates services based on its own name, not the prefixed name
# namePrefix: qwen3-

resources:
- model.yaml
- ../rbac/

patches:
- patch: |-
    - op: add
      path: /rules/0/resourceNames
      value: ["single-node-no-scheduler-nvidia-gpu"]
  target:
    kind: Role
    name: model-user
- patch: |-
    - op: replace
      path: /roleRef/name
      value: model-user
  target:
    kind: RoleBinding
    name: model-user-tier-binding

