apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-basic-deployment

# Deploy core infrastructure first
resources:
- ../../infrastructure
- ../kustomize-templates/models/simulator
- ../kustomize-templates/auth/api-keys