apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-gpu-deployment

# GPU cluster with both models
resources:
- ../../core-infrastructure
- ../kustomize-templates/models/simulator
- ../kustomize-templates/models/qwen3
- ../kustomize-templates/auth/api-keys
- ../kustomize-templates/auth/token-rate-limiting
- ../kustomize-templates/observability