# Admin API key secret for maas-api authentication
# Generate a secure admin key and replace the placeholder
---
apiVersion: v1
kind: Secret
metadata:
  name: maas-api-admin
  namespace: platform-services
type: Opaque
stringData:
  admin-key: "admin-key-placeholder"
