apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-platform-services-namespace.yaml
- 01-rbac.yaml
- 02-maas-api-deployment.yaml
- 05-external-access.yaml
- 06-admin-secret.yaml
- 07-maas-api-routing.yaml
- 08-reference-grant.yaml
- 09-maas-api-route.yaml
- 10-maas-api-auth-override.yaml
