# Fixed AuthPolicy - Enforces authentication and extracts identity
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: ai-auth
  namespace: openshift-ingress
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: openshift-ai-inference
  rules:
    authentication:
      api-key-bearer:
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: maas-api
        credentials:
          authorizationHeader:
            prefix: Bearer
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id || auth.identity.sub
                tier:
                  selector: auth.identity.metadata.annotations.tier || auth.identity.metadata.labels.tier || "default" 