apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-openshift-overlay

# Base configuration
resources:
  - ../../examples/gpu-deployment
  # OpenShift-specific additions
  - openshift-routes.yaml
