apiVersion: apps/v1
kind: Deployment
metadata:
  name: maas-api
spec:
  template:
    spec:
      containers:
      - name: maas-api
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-config
              key: DATABASE_URL

