name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Install kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s 5.7.1
        sudo mv kustomize /usr/local/bin/

    - name: Validate Kustomize manifests
      run: |
        ./scripts/validate-manifests.sh
