name: Key Manager

on:
  pull_request:
    paths:
      - 'key-manager/**'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: key-manager

    steps:
      - uses: actions/checkout@v5
  
      - uses: actions/setup-go@v5
        with:
          go-version-file: key-manager/go.mod
          cache: true
          cache-dependency-path: key-manager/go.sum
   
      - name: Check code formatting
        run: make fmt-check
        
      - name: Run tests
        run: make test
  
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            key-manager/coverage.out
            key-manager/coverage.html
          retention-days: 30
  
      - name: Build image
        run: make build-image

