name: Key Manager Build

on:
  pull_request:
    paths:
      - 'key-manager/**'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'

    - name: Check code formatting
      run: make fmt-check

    - name: Build image
      run: make build-image

